version: '2'
services:
    cautiondouane-app:
        image: cautiondouane
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cautiondouane-postgresql:5432/cautiondouane
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cautiondouane-postgresql:
        extends:
            file: postgresql.yml
            service: cautiondouane-postgresql
